### ISSUE TITLE
Doplnit generovany ibom.html o ID

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#17]
+ preferovane nastaveni
![Snímek z 2022-05-11 23-01-03](https://user-images.githubusercontent.com/12030407/167946998-bbb110bc-ffec-414d-a35d-cfb9339c9d73.png)
![Snímek z 2022-05-11 23-00-42](https://user-images.githubusercontent.com/12030407/167947000-944cf536-328c-4e5d-9ecd-65ded03e47dc.png)

**Comment by yaqwsx** [comment]
Implementováno v d048f6c33f8f5764bf81cf4ac90c3acebd44eb32

**Comment by ok1hra** [comment]
ID je pritomne, ale prazdne
![Snímek z 2022-05-17 10-50-36](https://user-images.githubusercontent.com/12030407/168771189-6ac88671-0b0d-40e1-b1c2-ffec96f5efde.png)

**Comment by yaqwsx** [comment]
Už vidím problém (zkoušel jsem na dosti specifikém příkladu), opravím.
