### ISSUE TITLE
Pevny adresar pro vystupni data

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#22]
Prave jsem si smazal cely projekt tim, ze jsem nasmeroval vystup do stejneho adresare.
Navrhuji tedy, aby vystupni data koncila v pevne danem podadresari (napriklad ./prusaman) hlavniho projektu.
Pouzivani by melo byt "blbuvzdorne" - prepsani vystupnich dat neni krize, daji se znovu vygenerovat, ale zdrojova data ne ;(

**Comment by yaqwsx** [comment]
Implementováno v ae1b309b28df58a3eb430f711f8dfd8e2b84e586
