### ISSUE TITLE
Nalezeni minimal drilling/guide width

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#25]
- [ ] Nalezt nejmensi vrtani na desce a doplnit tento udaj do readme
Stavajici format:
`- minimal drilling of {min-drill} mm - hole diameters are trailing - surface treatment immersive gold`
Soucasny stav je vice pranim, nez odrazem skutecnosti.

- [ ] stejna situace je u minimalni sirky spoje, coz nevim zda je implementovatelne
`- Minimum guide width / 0.2 mm gaps`

**Comment by yaqwsx** [comment]
Bod je 1 je bez problémů implementovatelný. U druhého bodu je problém s mezerou; napadají mě různá řešení:
- použít údaj z parametrů desky. Pokud deska prochází DRC (a to budeme kontrolovat), tak je údaj pravdivý.
- pokud je třeba znát skutečně minimální mezeru, tak bychom mohli neužít DRC a správnou hodnotu nalézt binárním vyhledáváním.

**Comment by ok1hra** [comment]
Pouzit udaj z parametru desky muzeme, ale implementovat az budeme kontrolovat DRC, jinak by mohl byt udaj nespravny.
Pokud ti prijde druha varianta schudnejsi, nejsem proti ;)

**Comment by yaqwsx** [comment]
Druhá variantu můžeme vyzkoušet; uvidíme, jak moc bude brzdit. Odhaduji, že bude znamenat zavolat cca 10 kontrolu DRC.

**Comment by yaqwsx** [comment]
Po několika experimentech jsem dospěl k tomu, že bude lepší kontrolovat DRC + číst hodnoty z návrhových pravidel. Kdyby bylo skutečně potřeba hledat nejmenší hodnoty, které deska má, tak můžeme předělat (jen mi teď nepřipadá, že by efekt stál za vynaložené úsilí).

Implementováno v 5039007
