### ISSUE TITLE
Reorganizace .zip archiv

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#26]
- [ ] Upresnim co maji obsahovat .zip archivy
Obecne jde ovsechny vystupni soubory daneho podadresare.
**/FREZA*/*.zip** (cely adresar gerber + readme.txt)
**/PANEL*/*.zip** (vse krome kicad souboru)
**/SMT*/*.zip** (obsah celeho adresare)

- [ ] Jeste prosim zmenit nazvy souboru readme a .zip, aby odpovidaly nazvum adresaru, ve kterych jsou. Jde o to, aby nebyly zamenitelne s jinym projektem, nebo jinou verzi stejneho projektu.

**Comment by yaqwsx** [comment]
Oboje zohledněno v d6f67b0, poprosím o kontrolu jestli jsme se pochopili správně. Kdyžtak upravím.

**Comment by ok1hra** [comment]
Potvrzuji ze je posledni verze spravne, diky
