### ISSUE TITLE
Prava souboru

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#28]
Na linuxu pri pouziti sdileneho sitoveho disku maji vystupni soubory Prusamana omezena prava.
Kolegove pak nemaji na sitovem disku k souborum pistup.
![Snímek z 2022-05-19 09-09-56](https://user-images.githubusercontent.com/12030407/169232351-5043b62b-41a9-4b50-a9d4-c269884e85ac.png)
Je mozne zmenit na -rw-rw-rw?

Stejny problem se tyka i samotnych zdrojovych souboru kicadu, kde je to jeste striktnejsi
![Snímek z 2022-05-19 09-13-53](https://user-images.githubusercontent.com/12030407/169232585-a3c9fd13-4448-43c9-b122-f6bac2b83f74.png)
coz nevim zda je v ramci prusamana resitelne...

**Comment by yaqwsx** [comment]
Toto bude způsobené kombinací toho, jak generuji výstupy:
- založím dočasný adresář, do kterého nageneruji všechny výstupy (proto, abych v případě chyby neničil existující výstup)
- následně provedu prohození cílového s tímto dočasným.
- 
Což povede k tomu, že cílový adresář bude mít přístupová práva stejná jako temp lokace. Můžu ale místo dočasného adresáře použít adresář v cílové lokaci a tím pádem dostat implicitní práva dané lokace.

**Comment by yaqwsx** [comment]
ba5c4ed by to mohlo řešit, ale nemám to u sebe jak otestovat.
