### ISSUE TITLE
Vytvorit archiv celeho projektu vcetne vystupnich dat

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#33]
Jako posledni krok pri generovani dat zaarchivovat zdrojova data do .zip
- nazev souboru stejny jako vystupni data [nazev projektu-verze].zip
- umisteni do rootu projektu

**Comment by yaqwsx** [comment]
Implementováno v fa3dcf3

**Comment by ok1hra** [comment]
Ma jit o zalohu, tedy nemelo by nic chybet.

**Comment by yaqwsx** [comment]
Problém s nekonečným zipováním vyřešen v ccaba7b
