### ISSUE TITLE
Verzi prusamana do vystupnich dat

### ISSUE THREAD

**Issue by ok1hra** [prusa3d/KiKIt_fab_prusa#35]
nekam do vystupnich dat (nemam jasno) vlozit verzi prusamana, se kterou byla data vytvorena.
Aby bylo jasne jake funce jiz byly implementovane a bylo mozne se vratit k exportu konkretni verzi.

**Comment by yaqwsx** [comment]
Přidám do kořene soubor `prusaman-info.txt`, kde můžeme všechna zajímavá metada vypisovat.

**Comment by ok1hra** [comment]
souhlasim, diky

**Comment by yaqwsx** [comment]
Přidal jsem `prusaman-info.txt` v 9cee2e13f514daf1421ed4accefaf925a8d3b734, který obsahuje:
- verzi
- čas generování
- a také přepis celého logu.
