### ISSUE TITLE
Sync 3D: Ošetřit chybějící kicad_sch

### ISSUE THREAD

**Issue by dzarda** [prusa3d/KiKIt_fab_prusa#39]
Chybějící schéma při kliku na *Sync 3D* by nemělo způsobit Unexpected Error, ale dát najevo selhání na straně uživatele.

![obrazek](https://user-images.githubusercontent.com/3955056/177168856-7da3db44-b720-4283-82f8-6eb3ad0da819.png)

**Comment by yaqwsx** [comment]
Opraveno v 6be0652
