### ISSUE TITLE
Sync Design Rules: Ošetřit chybějící proměnnou

### ISSUE THREAD

**Issue by dzarda** [prusa3d/KiKIt_fab_prusa#40]
Kliknutí na *Sync Design Rules* by nemělo způsobit Unexpected Error, ale dát najevo chybu na straně uživatele.

![obrazek](https://user-images.githubusercontent.com/3955056/177169112-fe1784b8-0a4e-4d91-95fe-b657b4c264fd.png)

**Comment by yaqwsx** [comment]
Opraveno v 6be0652
