### ISSUE TITLE
SETTINGS_MANAGER_LoadProject error

### ISSUE THREAD

**Issue by dzarda** [prusa3d/KiKIt_fab_prusa#64]
Tohle mi to už dvakrát vyhodilo při generování. Stačí pustit znovu a bez problému.

![obrazek](https://user-images.githubusercontent.com/3955056/192290382-1fd7b30d-3864-497c-b541-deae75e417b8.png)

`wx._core.wxAssertionError: C++ assertion "m_project_name.IsAbsolute()" failed at ..\..\common\project.cpp(101) in 
PROJECT::setProjectFullName():`

[prusaman-info.txt](https://github.com/prusa3d/KiKIt_fab_prusa/files/9646664/prusaman-info.txt)

**Comment by yaqwsx** [comment]
Mělo by být vyřešeno (příčina https://github.com/yaqwsx/KiKit/issues/421).
