### ISSUE TITLE
Přibalit KiKit k Prusamanovi

### ISSUE THREAD

**Issue by yaqwsx** [prusa3d/KiKIt_fab_prusa#8]
Jelikož je vývoj provázán, dává smysl, aby instalace nového Prusamana aktualizovala KiKit. Preferovaná varianta je přibalovat KiKit a instalovat oba doplňky.

**Comment by ok1hra** [comment]
Potrebe aktualizace KiKitu rozumim, nicmene - neznamena pribaleni KiKit do instalace Prusamana moznost jeho zastarani v pripade, ze nebude potreba Prusamana dale vyvijet?

**Comment by yaqwsx** [comment]
To je něco, nad čím dává smysl se v budoucnu ještě zamyslet - a je to spíše filozofická otázka (technicky je možné oboje):
- je možné se na to dívat tak, že Prusaman a KiKit pro vaše potřeby tvoří jeden balíček (který je +- zakonzervovaný a plní vaše potřeby). Pak přibalení dává smysl - zejména pokud KiKit někdy diverguje, tak tato varianta nezpůsobí nefunkčnost Prusamana.
- samotná případná aktualizace (v případě opravy chyby v KiKitu) je velmi jednoduchá - stačí ho v podstatě znovu zkompilovat a vydat novou verzi.
- Stále cílím na tom, že provázanost KiKitu a Prusamana je minimální a Prusaman spoléhá na stabilní rozhraní KiKitu. Tím pádem, v momentě, kdy si řekneme, že "takto to stačí", můžeme přestat přibalovat KiKit a držet upstream verzi.

**Comment by yaqwsx** [comment]
Přibalování implementováno v f1d7d703879c31843381e987cdf5d2ecd274181e.
